language: python
python:
  - 3.9.0
 # command to install dependencies
install:
  - pip3 install -r requirements.txt
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.0/bin/

  - export CHROME_BIN=chromium-browser
# command to run tests
script:
  - behave