language: python
python:
  - 3.9.0
 # command to install dependencies
install:
  - pip3 install -r requirements.txt
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d C:\Users\BONGA.DUBULA\.virtualenvs
  - export CHROME_BIN=chromium-browser
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
services:
 - xvfb
# command to run tests
script:
  - behave