language: python
python:
  - 3.7
  
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
 # command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - behave